server:
  port: 8888
api:
  prefix: /api/v1
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/test/identify/**
          filters:
#            - StripPrefix=2
            - RewritePath=/test/identify/(?<segment>.*), ${api.prefix}/auth-service/${segment}
        - id: course-service
          uri: http://localhost:8081
          predicates:
            - Path=/test/management/**
          filters:
#            - StripPrefix=1
            - RewritePath=/test/management/(?<segment>.*), ${api.prefix}/course-service/${segment}
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/test/client/**
          filters:
#            - StripPrefix=1
            - RewritePath=/test/client/(?<segment>.*), ${api.prefix}/user-service/${segment}
jwt:
  expiration: 3600
  secretKey: PstJjnP30Ohm2YKW/bgvGvk80UFeylLdzcbHcH136z4=